import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { anjoman } from "@/theme/fonts";
import theme from "@/theme";
import Rtl from "@/theme/rtl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${anjoman.variable} ${anjoman.className} antialiased`}>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <Rtl>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </Rtl>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
